// <auto-generated />
namespace Homework12_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class migrationFeb26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationFeb26));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261538009_migrationFeb26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
